name: DevOps Demo

on:
  workflow_dispatch:
    inputs:
      example_name:
        description: "Enter your name"
        required: true
        default: "Rohitha"

env:
  COURSE: DevOps

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Greeting
        run: echo "Hello, ${{ github.event.inputs.example_name }}!"

      - name: Runner Details
        run: |
          echo "Runner OS: $RUNNER_OS"
          echo "Runner Name: $RUNNER_NAME"

      - name: Print Course
        run: echo "Course: $COURSE"

      - name: Print Secret
        run: echo "My secret is ${{ secrets.MY_SECRET }}"
